on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: run tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
      - name: Run tests
        run: go test -v -covermode=count
